# 00.Pytorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


# Introduction to Tensors
### Creating tensors

PyTorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Get tensor back as Python int
scalar.item()

7

In [12]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim
# dimension is the number of square brackets

1

In [14]:
vector.shape

torch.Size([2])

In [6]:
#Matrix
Matrix = torch.tensor([[7,8], [9, 10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
Matrix.shape

torch.Size([2, 2])

In [15]:
#Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [10]:
TENSOR.ndim

3

In [13]:
TENSOR.shape
print(TENSOR.shape)

#what does it means?(torch.Size([1, 3, 3])??
#-> ONE dimension of 3 by 3 tensors

torch.Size([1, 3, 3])


In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors
why random tensors?

Random tensors are important because the way many neural networks learn is they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers 

Torch random tensors -https://pytorch.org/docs/stable/generated/torch.rand.html

In [29]:
#Create a random tensor of size (3, 4)
#rand() method returns a tensor filled with random numbers 
#from a uniform distribution on the interval [0, 1) 
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4119, 0.4931, 0.7971, 0.8606],
        [0.0158, 0.5300, 0.6238, 0.3613],
        [0.1010, 0.0148, 0.0794, 0.7556]])

In [28]:
# Create a radom tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height with color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [32]:
torch.rand(size = (3, 3))

tensor([[0.0522, 0.3937, 0.5428],
        [0.1676, 0.2990, 0.9232],
        [0.6173, 0.1270, 0.8499]])

## Zeros and ones

In [34]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
zeros*random_tensor

# it can mask all the particle outputs

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
# Create a tesors of all ones
ones = torch.ones(size= (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
ones.dtype

torch.float32

In [39]:
random_tensor.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [52]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])